### ISSUE TITLE
Sorry, I renamed the alpha release to a beta...

### ISSUE THREAD

**Issue by lukeapage** [bfricka/less-preview#10]
Please could you fix? Thanks.

**Comment by bfricka** [comment]
Sorry? That's progress! Congrats. I'll have it fixed when I get a chance tomorrow. :+1:

**Comment by bfricka** [comment]
And by tomorrow, I really mean later today

**Comment by lukeapage** [comment]
sorry because I haven't sorted out a proper system so that its easier to auto-detect...

**Comment by bfricka** [comment]
All set. I'm not too worried. When you come up with a process that makes you happy, let me know and as long as it's based on a set of rules, I'll write my code to accommodate. For now hardcoding isn't causing me any pain.

-Brian
