### ISSUE TITLE
Firefox not showing errors

### ISSUE THREAD

**Issue by lukeapage** [bfricka/less-preview#11]
in chrome for the following less I get an error

```
#test {
  .wrongMixin();
}
pre { //unrelated correct ruleset
  padding: 2 2 2 2;
}
```

in firefox though I see nothing...

**Comment by bfricka** [comment]
Can't reproduce in FF 19 Mac.  Help me out with version / OS please.

**Comment by lukeapage** [comment]
hrmm only happening for 1.4.0

This smells like a 1.4.0 bug. Leave it with me for now.

**Comment by bfricka** [comment]
Ahh sorry, I didn't check 1.4.0.  I'll leave this open for awhile just in case.

**Comment by lukeapage** [comment]
Think it is this

https://github.com/cloudhead/less.js/commit/dca9643a1ad8556d13b27dc960923b60ae5d9285

because you throw the error in the parse callback, you are relying on less to be synchronous and pass the exception on. I have fixed less to do this, as it used to.

Also I think it is not firefox specific it was because chrome was in 1.3.3...

**Comment by bfricka** [comment]
Makes sense, thanks.  I like the fact that we get useful error info, so if you do change it, let me know so I can tie back into it.
