### ISSUE TITLE
Make options more obvious

### ISSUE THREAD

**Issue by Soviut** [bfricka/less-preview#12]
Currently, there is a rather empty header with one lonely dropdown called "options". Without this menu/drawer being open, one cannot tell what version or settings are being used. Any newcomers who don't recognize this may not realize what version or settings they're using to test.

I propose these options be put in a header or sidebar that is visible by default and be hidden/minimized at the user's choosing.

Additionally, given the expectation that, at some point, the ability to save snippets will be possible, it would make sense to display the options prominently so that people could see what settings were used to arrive at a particular result.

**Comment by bfricka** [comment]
You make some very good points.  I think the options button itself is quite obvious, and I am reluctant to remove the options dropdown and instead put everything in the header itself. Mainly, I think that the number of options will likely grow at some point and down want to have things get cramped.

That said, there is a real information problem as you stated.  I'll add something that displays the current state of all the options somewhere.  The header has plenty of real-estate on large screens so I'll look there first.

I'm in the midst of a pretty large refactor on another branch that will see the project converted to javascript and introduce the beginnings of the github oauth stuff required logging in (and thus storing snippets). I'll get this in as soon as I can.

Thanks.

**Comment by Soviut** [comment]
At the very least, show the options by default. Otherwise, nobody is going to know when then default changes from 1.3.3 to 1.4, for example.

A sidebar like JSFiddle may be the ideal way to cope with a need for expanded options.

**Comment by bfricka** [comment]
I made a few UI tweaks which should hopefully satisfy the poor option visibility.  Let me know if you have any additional suggestions
