### ISSUE TITLE
Less2css.org site down

### ISSUE THREAD

**Issue by scottgit** [bfricka/less-preview#18]
@brian-frichette The less2css.org site has been down for over a day at least now. Were you aware of that?

**Comment by lukeapage** [comment]
was just about to raise it myself...

**Comment by bfricka** [comment]
Thanks for the heads up. I noticed this but I have been on an airplane all day and have been unable to investigate. 

I'll be home finally in an hour and a half, so I'll have it hopefully fixed shortly thereafter.

**Comment by bfricka** [comment]
Everything is fine. It looks like my VPS went down w/out warning me.  I'm going to make sure this doesn't happen again by opening and implementing two issues here (creating a startup script so my proxy / node servers start-up automatically, and also looking into getting some admin alerts / logging so I can be informed about bad news quickly).

Thanks for reporting here.

**Comment by scottgit** [comment]
@brian-frichette I hope you are moving toward full health in your continued recovery from your accident. I wanted you to know that your site has been down again for over a week now.

**Comment by evalica** [comment]
Still down. Not sure what is the right process in this case. Thanks

**Comment by bfricka** [comment]
Sorry guys, it should be back up now. Recovery's been slow, but I'm getting there, so hopefully soon I can write something that ensures this won't occur again.

**Comment by scottgit** [comment]
@brian-frichette And down again :-) (for a couple days now).

**Comment by bfricka** [comment]
Insanity. I'll be able to fix this crap for good this weekend. Sorry for neglect. It's back up... for now :-P

**Comment by ghost** [comment]
In case anyone else needs a quick alternative: http://lesstester.com

**Comment by lukeapage** [comment]
@brian-frichette anything I can do to help? you can message me privately if you need.

**Comment by bfricka** [comment]
Thanks @lukeapage .  I'm getting my functioning back on track so I'm good.  I got an SSH app for my phone so I can quickly start the server if it goes down again.  Hoping I'll have time to create a start-up script so I can forget about this (the app runs on node-forever, so it's only when the server goes down for maintenance).

System admin stuff really bores me, so I haven't had the highest level of motivation. Sorry.

**Comment by lukeapage** [comment]
@brian-frichette seems to be down again!

**Comment by bfricka** [comment]
Thanks @lukeapage I'll have this closed out this weekend for sure. For now, it's back up.

**Comment by lukeapage** [comment]
@brian-frichette its down again.. what was the reason for needing a custom server again instead of through git hosting?
I'm wondering whether the page could just scrape the CDN for versions or even have them hard-coded if its going to make things more stable.
I'd rather remove the link from lesscss.org if its going to be more down than up..

**Comment by bfricka** [comment]
Understood and agreed. I'd like to keep this around for awhile and would ask that you give me a day or two. I just have to finish migrating it to EC2, and simply haven't given it the priority it deserves.

**Comment by bfricka** [comment]
@lukeapage I have migrated the site to EC2. I'll be tweaking a few things over the next day or two but it should be stable thereafter. I'll focus on pulling versions automatically ASAP.
