### ISSUE TITLE
Update site w/ 1.4.2 release

### ISSUE THREAD

**Issue by bfricka** [bfricka/less-preview#19]

**Comment by scottgit** [comment]
Now it needs to be updated to 1.5.0 also, since that release just recently came out.

**Comment by bfricka** [comment]
Shit. Yeah I think I made all the changes for 1.4.2 but never deployed them. I will take care of this. Thanks for bringing it up

**Comment by paazmaya** [comment]
Would it be possible to allow user to switch between versions, perhaps via drop down menu?
This might make it easier to pin point library related issues when trouble shooting.

**Comment by bfricka** [comment]
Hi, Juga,

This functionality already exists. Just hit the options button and a panel
will drop down where you can choose your version.

**Comment by scottgit** [comment]
@brian-frichette I'm just checking up on the deploying of 1.4.2 and 1.5. You had mentioned over two weeks ago that you would "take care of this," but I also know you have a life :-). Anyway, I just wanted you to know that I, for one, really appreciate the site and use it for all my testing of LESS. So thank you for your work and time you do put in on it.

**Comment by bfricka** [comment]
Yes, I'm going to get to it soon. I was involved in motorcycle accident
where I fractured my right clavicle, and had to undergo surgery to put the
pieces together. It's been pretty shitty, honestly.

Wearing a sling means typing with my left hand only (I'm right handed).

Anyways, I'll be better soon

**Comment by scottgit** [comment]
@brian-frichette Oh, sorry to hear about that! Sounds like we should be thankful that you can type at all; a motorcycle accident could have ended up FAR worse. Glad you will be better soon.

**Comment by lukeapage** [comment]
Yes, get better soon, sorry to hear it. Take care!

**Comment by bfricka** [comment]
Updated to 1.5.1. Thanks for the patience.

**Comment by scottgit** [comment]
@brian-frichette I'm not seeing a selection in the Options drop down for the LESS version for anything beyond 1.4.1, which it is still saying is "current."

**Comment by bfricka** [comment]
Yeah, I didn’t fully merge the in progress stuff I was working on so I believe there is a bug in the expiration of localStorage which is persisting the options longer than it should.  Even so I should write something that periodically (like once a day) looks for new options and merges them into the user options so selected prefs can be kept while new options are added.

Either way, you can clear your localStorage and refresh and you’ll get the new stuff.  Sorry bout that.
