### ISSUE TITLE
Synchronized Scrolling

### ISSUE THREAD

**Issue by Anticom** [bfricka/less-preview#20]
Hi,
I thought it would be awesome, if you could sync the scrollbars.
The problem I see, is that it isn't enough to just sync up their absolute position but it would have to match the selectors somehow, kind of how you see it in 3-way-merge editors sometimes.
`one [nested] less selector` <-> `[eventually] multiple output selectors`

Cheers, good work so far!

**Comment by lukeapage** [comment]
You could use sourcemaps to sync them.. but its a tremendous effort for a
little gain!

**Comment by bfricka** [comment]
Not a bad idea @lukeapage, except source map support was added in 1.5, right? So it would have to be an option (enabled by default in 1.5).

Am I looking at this correctly?

**Comment by lukeapage** [comment]
Yes and there is not yet client side support for sourcemaps...

**Comment by Anticom** [comment]
Just a little ping on my Ticket, since it's still open.
I've just discovered, that there seems to be a [source map implementation](https://github.com/mozilla/source-map) in js now (done by mozilla).
I am not a JS dev so I can't really tell, wether you could use that one or not.
