### ISSUE TITLE
1.6.0 released

### ISSUE THREAD

**Issue by lukeapage** [bfricka/less-preview#24]
Another release!

**Comment by bfricka** [comment]
Congrats. I'll add it tonight :)

On a side note, I've been learning about how to configure start-up stuff on linux so I'll be able to finally close that [less2css is down](https://github.com/brian-frichette/less-preview/issues/18) bug. Finally.

I'm also working on further componentizing the code so we can integrate simple editors for the code samples on lesscss.org documentation page (similar to [coffeescript.org](http://coffeescript.org)).

**Comment by bfricka** [comment]
All set
