### ISSUE TITLE
1.6.1 - 1.6.3 released, rumors 1.7.0 coming soon

### ISSUE THREAD

**Issue by scottgit** [bfricka/less-preview#26]
Just noting that the site is behind by a few updates. Thanks for your work on this. I know you are attempting to get auto-updating worked out.

**Comment by bfricka** [comment]
I was... It's not particularly difficult. But I'm not really linked on lesscss.org any longer so I do sort of wonder to what extent this project will continue to even get traffic? I can check Google Analytics.

Either way, I'll make this happen :)

Thanks for the heads up.

**Comment by scottgit** [comment]
You are [still linked](http://lesscss.org/usage/#online-less-compilers) and at the top.

**Comment by bfricka** [comment]
Gotcha. Yeah traffic's been cut in half but it still seems to receive around 1,500 page views a week.

I have a question since I know you've answered many SO questions on LESS... What's your impression in terms of usage of legacy versions of LESS?  The main initial motivation for creating this site was to test feature differences between versions since certain projects or apps are stuck on older versions.

However, I'd like to prune some of old stuff if possible.

**Comment by scottgit** [comment]
I cannot honestly answer what actual "usage" of the legacy versions of LESS are. What I can say, however, is that your legacy versions are precisely why I use and prefer your site above all others for testing. Oftentimes I want to know how a particular coding works in relation to older versions, and it is _so easy_ to just switch through versions an see where something fails, or suddenly starts working. I don't know what type of maintenance it takes for you to keep the older versions, but my thought is, if "not much," then keep it--because that is what makes your site so valuable.

**Comment by bfricka** [comment]
No maintenance required at all. :) Thanks for the reply

**Comment by scottgit** [comment]
No problem. I guess I could see where the list may simply get too long to be user friendly in a drop down. Maybe at some point the older versions should be moved to some "sub selection" area and not part of the main drop down selection. Make them available, but not without a little bit of digging to get to them.

**Comment by bfricka** [comment]
Done. I'm going to start working on this again and get 2+ support soon.
