### ISSUE TITLE
Update for LESS 1.7 release

### ISSUE THREAD

**Issue by scottgit** [bfricka/less-preview#27]
LESS 1.7 was released 14 days ago. Also, for historical support, the site is not updated for 1.6.1 - 1.6.3 releases either.

**Comment by bfricka** [comment]
Yes... I will get this today. I've been working on a refactor of certain things (an automated git tag checker is part of the mix) so I've been putting off the update. I'll make sure to get the new versions out today, though.

Thanks.

**Comment by bfricka** [comment]
Done
