### ISSUE TITLE
1.7.0 support

### ISSUE THREAD

**Issue by SomMeri** [bfricka/less-preview#28]
Could you please add support for less.js 1.7.0 (latest)?  Less.js dist repo link: https://github.com/less/less.js/tree/master/dist

**Comment by bfricka** [comment]
I totally will. I'm out of town right now at Joshua Tree, but I've been meaning to finish that off for awhile now. Thanks.

**Comment by tomByrer** [comment]
How about [v1.7.5](https://github.com/less/less.js/commit/08e2fc413675ea06426f9b9b532efbb2d600ea0b) please?

**Comment by bfricka** [comment]
Done. Finally. I'll be working on this again, so 2+ will be out soon.
