### ISSUE TITLE
less options

### ISSUE THREAD

**Issue by lukeapage** [bfricka/less-preview#6]
less has quite a few options now - maybe the appropriate ones could be exposed?

**Comment by bfricka** [comment]
Can you explain specifically what you are referring to by "options"? Thanks.

**Comment by aziz** [comment]
:+1: 
I would like to change `line-numbers` option and see the output, for new less versions ( >= 1.3 I guess)

--line-numbers=TYPE     

```
                      Outputs filename and line numbers.
                      TYPE can be either 'comments', which will output
                      the debug info within comments, 'mediaquery'
                      that will output the information within a fake
                      media query which is compatible with the SASS
                      format, and 'all' which will do both.
```

**Comment by scottrippey** [comment]
Sifting through the less source, I saw a couple of what I think are "options" ... but I'm not sure where they're documented.
@agatronic Can you provide some insight or documentation for these less options?  Or perhaps, it would be better to refactor them into an isolated object, such as `less.options`?
Examples:

```
less.dumpLineNumbers = 'comments' | 'mediaquery' | 'all' // Outputs line numbers in the CSS
less.relativeUrls = true | false
less.rootpath = 'some path used for relativeUrls'
less.env = 'development' // Enables console logging, and insertion of the error message
```

**Comment by lukeapage** [comment]
they are documented (albeit not so well) on the website

http://www.lesscss.org/#usage

I only added that section a couple of weeks ago. I agree less.options would be a much better place to put them, but that is a breaking change- people are using these options even though they are (or were) badly documented.

**Comment by bfricka** [comment]
Gotcha.  I'll take care of this.

**Comment by bfricka** [comment]
Added options on 0.0.3

There's still some polishing to do (add tooltips, etc.)

Please test and suggest :)

**Comment by lukeapage** [comment]
cool, looks good.

When I enter a rootpath the characters get url encoded - is that a less2css bug or a less bug? I think it is a less2css bug.

**Comment by bfricka** [comment]
I think you're right. Off the top of my head, I think it's probably the form modeler that I wrote (I think I am going to abstract that piece to a separate module anyways since it's useful elsewhere).  Thanks, will fix tonight.
