### ISSUE TITLE
CSS output line numbers

### ISSUE THREAD

**Issue by gustavohenke** [bfricka/less-preview#8]
Hey,
This is not something veeery required, but maybe would be useful to have the line numbers in the CSS output.

Thanks!

**Comment by bfricka** [comment]
Are you referring to gutter line numbers?  For the CSS output?

I recently implemented options to dump line numbers from the less files into the CSS, but I'm thinking that you're referring to the gutter line numbers?

**Comment by gustavohenke** [comment]
That's right.

**Comment by bfricka** [comment]
Uh huh. Well, I'm not opposed b/c it makes the app simpler as I can remove highlight.js and just use another CodeMirror instance. I don't really care about the line numbers, but I'll enable them.  Mainly I like the idea of being able to select all on the CSS side.

I'll get this implemented soon, thanks.

**Comment by bfricka** [comment]
This is done on the latest release.
