### ISSUE TITLE
more options

### ISSUE THREAD

**Issue by lukeapage** [bfricka/less-preview#9]
1.4.0 now has strictUnits and strictMaths options (you might consider combining into legacy?) they default to true and will be quite important for 1.4.0.

Also.. does your project require a new build to update to the new alpha version?

Thanks!

**Comment by bfricka** [comment]
Hi Luke,

Regarding the alpha builds: For now I will setup a cron job to curl the alpha script every 6 hours or so it stays up to date. I'll get that implemented ASAP.

Regarding options, I can easily add those to the options drawer. Are you suggesting that they act as a single option (both strictUnits and strictMaths are activated) or would you prefer them separate?

I was also wondering if there are any other options that might be useful.  Looking at the code, I saw both a minify option and an optimization level option.  Playing with them, minify works fine, but I was unable to determine what, if anything, the optimization number does. Changing that value from 0-3 didn't seem to produce any different output.

Finally, I noticed there are a few pull requests over at lesscss.org (including my own).  If you would like some help maintaining that, I would be happy to do so.

I'll have this stuff implemented as soon as I get a minute.

-Brian

**Comment by bfricka** [comment]
BTW, the reason I don't just link to the github raw output for the alpha is b/c github sets the content-type to text/plain on raw files, and IE9 and IE10 won't execute the script with mismatching content-type.

**Comment by lukeapage** [comment]
strictMaths and strictUnits are seperate options that both default to true in 1.4.0 You can set them to false, which makes less behave in a way backwards compatible with 1.3.3

optimisation effects the way the parser "chunks" and only effects the speed of compilation.

lesscss.org - I'd forgotten about that. 2 or 3 of the pulls are waiting for 1.4.0 but I should really pull the others - its no hassle to do the pulling and I can deploy then, I'd just forgotten.

What we really need help with is coding - fixes and features (https://github.com/cloudhead/less.js/issues?milestone=4&state=open) since we have a few people helping with documentation and talking about features, but only me willing to actually code them. If you do fancy helping, I suggest you write about a suggested fix in the issue before doing it (unless its a no brainer) to save it getting coded up with the wrong fix.

**Comment by bfricka** [comment]
I'm glad to help with coding.  I'll run through the list and pick something that strikes me :)

**Comment by lukeapage** [comment]
great.. the 2 assigned to me I am working on. just add a comment on any you want to try and I'll make sure everything you need to know is in that issue.

**Comment by bfricka** [comment]
Hi Luke,

I setup a cron task that pulls the alpha file every 10 minutes.  Currently, the file it's pulling is causing errors. `non_object_property_load error: Cannot read property 'compress' of undefined`.  I'm really sleepy right now, so I'm not going to get into debugging it, but I thought I would let you know that alpha changes will reflect (relatively) quickly now.

I'll add the legacy option for `strictMaths` and `strictUnits` very soon.

**Comment by lukeapage** [comment]
@brian-frichette thanks, guess thats why it says options is not defined for 1.4.0 alpha at the moment

let me know if its something we have done...

**Comment by bfricka** [comment]
I believe it is on the less.js side. I haven't changed anything in terms of how I instantiate or interact with instances of less. I will dig deeper to try to diagnose the problem when I get some time, if you don't get to it first. This is a particularly busy week for me.

**Comment by lukeapage** [comment]
@brian-frichette you are right. I have fixed it - you were passing null as the options and less.js didn't like it. It was a bug. However, you need to pass the options object to the parser and the toCSS() call (first argument) otherwise it won't pick up some of the new options.. Thanks.

**Comment by bfricka** [comment]
Awesome. I'll make the changes when I get home tonight. Thanks!

**Comment by bfricka** [comment]
Sorry that took so long. Was out of town this weekend.

Take a look and let me know if I missed anything. :+1:

**Comment by bfricka** [comment]
BTW @agatronic, I'm looking at the open issues, and I'm going to see if I can help out.  However, there is no way for me to see which are assigned to you (since I'm not a collaborator on the repo). Can you let me know which tickets you are specifically working on so I can stay away from them?

Thanks,

**Comment by lukeapage** [comment]
just variable `@import`s - thats my project at the moment.

Many thanks - just add a comment on the bug saying you are taking a look as
I know there are a couple of other people who said they might help out (but
they are yet to contribute anything).

this one

https://github.com/cloudhead/less.js/issues/1067
and
https://github.com/cloudhead/less.js/issues/1092

should be relatively easy

this one
https://github.com/cloudhead/less.js/issues/442

shouldn't be too difficult.

All are planned for 1.4.0. Of course if you would like to do something for
1.4.1 or something more meaty like the import options, that is cool too.

**Comment by bfricka** [comment]
I believe I'll stick to the easier stuff until I familiarize myself with the codebase :)
